### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by adyprat** [deezer/gravity_graph_autoencoders#1]
Very cool paper! Are you planning to make the code available anytime soon? Asking for a friend. :smile: 
Thank you,
-Aditya

**Comment by GuillaumeSalhaGalvan** [comment]
Thanks! The code is currently under review on our side, it should be available by the end of November.

**Comment by GuillaumeSalhaGalvan** [comment]
Dear @adyprat,
The code is now available! I am closing this issue.
Best,
Guillaume
