### ISSUE TITLE
pytorch implementation

### ISSUE THREAD

**Issue by cxw-droid** [deezer/gravity_graph_autoencoders#10]
The idea in this paper is interesting. Would you mind providing a PyTorch implementation? Thanks.

**Comment by GuillaumeSalhaGalvan** [comment]
Dear @cxw-droid,

Thank you for your message and your interest. I apologize for the late reply - this issue, unfortunately, went under my radar.

Our team does not currently plan to develop a PyTorch version. However, I'd be happy to review any implementation. The GAE/VGAE code provided in [pytorch_geometric](https://github.com/pyg-team/pytorch_geometric) should be a good starting point.

Best,

Guillaume

**Comment by ClaudMor** [comment]
Hello @GuillaumeSalhaGalvan ,

Sorry for reopening this. I'd have a working torch_geometric-based implementation of your experiments. Even though I'm using fully custom code (except for the data loading and splitting functions that I took directly from this repo), I think the results are being properly reproduced.

Right now, it is limited to the gravity-GAE, gravity-VGAE and SourceTarget-GAE models (on all three tasks). I should be able to add the SourceTarget-VGAE with little effort. It presents a few additions, in the form of:

- Trainable lambda coefficient (can also be fixed)
- New training strategy for the biased scenario (task 2)

Using the last trick, the SourceTarget-GAE in the biased scenario jumps from 57 AUC reported in your article to >80 AUC . The gravity models slightly improve too. Training lambda is sometimes beneficial.

Would you still be interested in reviewing a PR?

**Comment by GuillaumeSalhaGalvan** [comment]
Looks amazing @ClaudMor.
Sure, I would be glad to check it out!

Feel free to reach out (my email is available [here](https://guillaumesalhagalvan.com/)) to provide details about these additions and/or specific parts of your code that would require a closer look. We'll discuss.

**Comment by GuillaumeSalhaGalvan** [comment]
Update for future readers: @ClaudMor's code is now publicly available [here](https://github.com/ClaudMor/gravity_gae_torch_geometric)!
