### ISSUE TITLE
should we dropout the latent_z?

### ISSUE THREAD

**Issue by chansigit** [deezer/gravity_graph_autoencoders#11]
Dear authors,

I am wondering if we should perform dropout on the input_z instead of of the full latent vector, since the mass is vital and should not be dropped?
https://github.com/deezer/gravity_graph_autoencoders/blob/fa098943ad8b25de14882d76f3ad08253b30ab35/gravity_gae/layers.py#L154

**Comment by GuillaumeSalhaGalvan** [comment]
Dear @chansigit,

First of all, thank you for your message and interest! :)

This is a relevant comment. Honestly, we mainly included this line in the code for consistency with respect to standard GAE/VGAE models, as the gravity-inspired GAE/VGAE models presented [in the paper](https://arxiv.org/pdf/1905.09570.pdf) do not use dropout. But, yes, I agree that performing dropout only on the z_i vectors should be the best way to proceed in this case, considering the role of the mass.

Guillaume

**Comment by chansigit** [comment]
Got it. Thank you!
